name: Analysis

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master

env:
  intercepter_outFile: './.intercepter/ci_debug.md'

jobs:
  setup:
    strategy:
      fail-fast: false
      matrix:
        node:
          - '16'
        platform:
          - macos-latest

    name: Build Check on '${{ matrix.platform }} / Node.js v${{ matrix.node }}'
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Configure Git
        run: |
          git config --global core.autocrlf false
          git config --global user.name "xyz"
          git config --global user.email "x@y.z"

      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Create Env File
        run: |
          touch .env
          echo 'ENV=GITHUB_CI' >> .env
          echo 'ENV_OUTPUT=${{ env.intercepter_outFile }}' >> .env

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Pnpm
        run: npm install -g pnpm@7.25.0

      - name: Install Dependencies
        run: pnpm install

      - name: Build Prepare
        run: pnpm run build:prepare

      - name: Build Blog with debug
        run: pnpm run build:debug

      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ${{ env.intercepter_outFile }}
