name: 发布博客

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: 输入发布分支
        required: true
        default: master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  setup:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest

    name: 发布流程 ${{ matrix.platform }}
    environment: github-pages
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Configure Git
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global user.name "ci-robot"
          git config --global user.email "robot@git"

      - name: Checkout Commit
        uses: actions/checkout@v6
        with:
          lfs: false
          fetch-depth: 1

      - name: Set LFS Cache
        uses: './.github/actions/lfs-cache'

      - name: Setup Environment
        uses: './.github/actions/setup-env'

      - name: Build Prepare
        run: pnpm run build:prepare

      - name: Build Blog
        run: pnpm run build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
