name: 发布博客

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: 输入发布分支
        required: true
        default: master

jobs:
  setup:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macos-latest

    name: 发布流程 ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Configure Git
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global user.name "ci-robot"
          git config --global user.email "robot@git"

      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
          lfs: false
          fetch-depth: 1

      - name: Setup Git
        uses: './.github/actions/lfs-cache'

      - name: Setup Environment
        uses: './.github/actions/setup-env'

      - name: Build Prepare
        run: pnpm run build:prepare

      - name: Build Blog
        run: pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./dist
          force_orphan: true
