name: Github Pages

on:
  pull_request:
    types: [closed]
    branches:
      - master

  push:
    branches:
      - master

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        node:
          - '16'
        platform:
          - ubuntu-21.04
          - windows-2021
        storeDir:
          - '\.pnpm-store'

    name: '${{ matrix.platform }} / Node.js v${{ matrix.node }}'
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Configure Git
        run: |
          git config --global core.autocrlf false
          git config --global user.name "xyz"
          git config --global user.email "x@y.z"

      - name: Checkout Commit
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install Pnpm
        run: |
          npm install --g pnpm@6.32.0
          pnpm --version

      - name: Set Cache Directory
        run: 'pnpm config set store-dir ${{ matrix.storeDir }}'

      - name: Get Cache Directory
        id: pnpm-cache-dir
        run: echo "::set-output name=dir::$(pnpm config get cache)"

      - name: Restore Cache Data
        uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: ${{ matrix.storeDir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: pnpm install

      - name: Check Code Style
        run: pnpm run lint

      - name: Build Prepare
        run: pnpm run build:builder

      - name: Build Blog
        run: pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
